### ISSUE TITLE
2016-08-02 ~ ToDo List

### ISSUE THREAD

**Issue by theo-armour** [Abantech/abantech.github.io#6]
@Abantech/core 
## Profile

Fill in the bits here:
- [Profile](https://github.com/organizations/Abantech/settings/profile)
## People

Make sure everybody that should be here is here and public:
- [People](https://github.com/orgs/Abantech/people)
## Issues

Learn to create and close issues - and [learn how to add new labels](https://help.github.com/articles/creating-and-editing-labels-for-issues-and-pull-requests/) to issues

Close issue #5 or create a presence for such dialog?

---

And maybe learn some MarkDown...

**Comment by theo-armour** [comment]
@GMelencio 

Anybody here?

**Comment by GMelencio** [comment]
I updated the profile. I am looking forward to posts from others as well.
James just includewd DOxygen in our build process which makes our new C++
libs self-documenting. Looking forward to that post!

Greg Melencio
CEO and Founder
Abantech LLC
571-402-4688

**Comment by theo-armour** [comment]
@GMelencio 

looks good. closing...
